services:

  mysql-dbt:
    image: mysql:8.0
    container_name: mysql-dbt
    command: --secure-file-priv=""
    ports:
      - "3306:3306"
    env_file:
      - .env

    volumes:
      - ./csv_files:/opt/airflow/data/csv_files
      - ./sql_files:/opt/airflow/data/sql_files
      - mysql-dbt-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  mysql-dbt-volume: